// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCctp10xDBLPOTjXVZxjKbVgJYAcMEvd5E',
    appId: '1:636559461088:web:a2737aacbd959e3a8c1e85',
    messagingSenderId: '636559461088',
    projectId: 'movies-app-5ef96',
    authDomain: 'movies-app-5ef96.firebaseapp.com',
    storageBucket: 'movies-app-5ef96.firebasestorage.app',
    measurementId: 'G-GVH3JJ80YL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF9pyzruURffWIahooKOEZGuIDvLUsKiY',
    appId: '1:636559461088:android:12059375c65ea7608c1e85',
    messagingSenderId: '636559461088',
    projectId: 'movies-app-5ef96',
    storageBucket: 'movies-app-5ef96.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtNMqDC2CxFLy6sSNcgxIlIxmOW_ELTn4',
    appId: '1:636559461088:ios:7fb9b0c307f8c5d88c1e85',
    messagingSenderId: '636559461088',
    projectId: 'movies-app-5ef96',
    storageBucket: 'movies-app-5ef96.firebasestorage.app',
    iosClientId: '636559461088-4gisq1not3oi3j1ppkfebfhgugi80374.apps.googleusercontent.com',
    iosBundleId: 'com.example.movies',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtNMqDC2CxFLy6sSNcgxIlIxmOW_ELTn4',
    appId: '1:636559461088:ios:7fb9b0c307f8c5d88c1e85',
    messagingSenderId: '636559461088',
    projectId: 'movies-app-5ef96',
    storageBucket: 'movies-app-5ef96.firebasestorage.app',
    iosClientId: '636559461088-4gisq1not3oi3j1ppkfebfhgugi80374.apps.googleusercontent.com',
    iosBundleId: 'com.example.movies',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCctp10xDBLPOTjXVZxjKbVgJYAcMEvd5E',
    appId: '1:636559461088:web:aa23b8bb17b28f258c1e85',
    messagingSenderId: '636559461088',
    projectId: 'movies-app-5ef96',
    authDomain: 'movies-app-5ef96.firebaseapp.com',
    storageBucket: 'movies-app-5ef96.firebasestorage.app',
    measurementId: 'G-XMEZT0NH0L',
  );

}